export const teamData = [
  {
    unique: "SEMNASTI2025-A1BCD",
    name: "Dimas Aryaputra",
    nim: "A11.2022.12001",
    email: "dimas.arya@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-A2EFG",
    name: "Rama Danu Pradipta",
    nim: "A11.2023.12002",
    email: "rama.danu@students.example.com",
    present: false,
  },
  {
    unique: "SEMNASTI2025-A3HIJ",
    name: "Kevin Prasetyo",
    nim: "A11.2021.12003",
    email: "kevin.pras@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-A4KLM",
    name: "Alif Nur Hidayat",
    nim: "A11.2020.12004",
    email: "alif.hidayat@students.example.com",
    present: false,
  },
  {
    unique: "SEMNASTI2025-A5NOP",
    name: "Rizky Faizal",
    nim: "A11.2024.12005",
    email: "rizky.faizal@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-A6QRS",
    name: "Bagas Ardiansyah",
    nim: "A11.2022.12006",
    email: "bagas.ardi@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-A7TUV",
    name: "Yuda Permadi",
    nim: "A11.2023.12007",
    email: "yuda.permadi@students.example.com",
    present: false,
  },
  {
    unique: "SEMNASTI2025-A8WXY",
    name: "Rafi Maulana",
    nim: "A11.2021.12008",
    email: "rafi.maulana@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-A9ZBC",
    name: "Fikri Wahyudi",
    nim: "A11.2020.12009",
    email: "fikri.wahyudi@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-B1DEF",
    name: "Teguh Pramudya",
    nim: "A11.2024.12010",
    email: "teguh.pramudya@students.example.com",
    present: false,
  },
  {
    unique: "SEMNASTI2025-B2GHI",
    name: "Akbar Yusman",
    nim: "A11.2021.12011",
    email: "akbar.yusman@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-B3JKL",
    name: "Hafiz Rahmad",
    nim: "A11.2023.12012",
    email: "hafiz.rahmad@students.example.com",
    present: false,
  },
  {
    unique: "SEMNASTI2025-B4MNO",
    name: "Rendy Julian",
    nim: "A11.2022.12013",
    email: "rendy.julian@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-B5PQR",
    name: "Darma Wijaya",
    nim: "A11.2020.12014",
    email: "darma.wijaya@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-B6STU",
    name: "Jovan Surya",
    nim: "A11.2024.12015",
    email: "jovan.surya@students.example.com",
    present: false,
  },
  {
    unique: "SEMNASTI2025-B7VWX",
    name: "Galih Fatur",
    nim: "A11.2021.12016",
    email: "galih.fatur@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-B8YZA",
    name: "Ilham Nugraha",
    nim: "A11.2023.12017",
    email: "ilham.nugraha@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-C1BCD",
    name: "Agung Perdana",
    nim: "A11.2022.12018",
    email: "agung.perdana@students.example.com",
    present: false,
  },
  {
    unique: "SEMNASTI2025-C2EFG",
    name: "Devan Rasyid",
    nim: "A11.2020.12019",
    email: "devan.rasyid@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-C3HIJ",
    name: "Farhan Aditya",
    nim: "A11.2024.12020",
    email: "farhan.aditya@students.example.com",
    present: false,
  },
  {
    unique: "SEMNASTI2025-C4KLM",
    name: "Hilmi Ramadhan",
    nim: "A11.2023.12021",
    email: "hilmi.ramadhan@students.example.com",
    present: true,
  },
];
